image: Visual Studio 2015

branches:
    only:
        - master
        - appveyor-config
        
build_script:
    - cmd: mklink /D c:\git "C:\Program Files\Git"
    - cmd: set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
    - cmd: set PATH=c:\git\usr\bin;%PATH%;C:\MinGW\bin
    - cmd: copy windows\make.exe \git\usr\bin
    - cmd: set CMAKE_MAKE_PROGRAM=c:\git\usr\bin\make.exe
    - cmd: set APPVEYOR=TRUE
    - cmd: sh build_windows.sh
    - cmd: build.bat
    
deploy: off
test: off
