image: Visual Studio 2015

branches:
    only:
        - master
        - appveyor-config
        
environment:
    appveyor: true
    
build_script:
    - cmd: sh build_windows.sh
    - cmd: build.bat
    
deploy: off
test: off
