image: Visual Studio 2015

branches:
    only:
        - master
        - appveyor-config
        
environment:
    appveyor: true
    
build_script:
    - cmd: mklink /D c:\git "C:\Program Files\Git"
    - cmd: set PATH=c:\git\usr\bin%PATH%;C:\MinGW\bin
    - cmd: sh build_windows.sh
    - cmd: build.bat
    
deploy: off
test: off
