image: Visual Studio 2015

branches:
  only:
    - master
    - appveyor-config

cache:
  - build_ext  # uncache this if external deps change (eg. SDL_mixer 2.0.3 gets released)

init:
  - dir "C:\Program Files\Git"
  
build_script:
  - mklink /D c:\git "C:\Program Files\Git"
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=c:\git\usr\bin;%PATH%;C:\MinGW\bin
  - copy windows\make.exe \git\usr\bin
  - set CMAKE_MAKE_PROGRAM=c:\git\usr\bin\make.exe
  - set APPVEYOR=TRUE
  - sh build_windows.sh
  - build.bat

test: off

after_build:
  - copy c:\mingw\bin\libgcc*.dll .
  - copy c:\git\mingw32\bin\libstd*.dll .
  - copy build_ext/built_sdl/bin/SDL*.dll .
  - copy build_ext/built_sdl_mixer/bin/SDL*.dll .
  - 7z a systemshock.zip systemshock.exe *.dll 

artifacts:
  - path: systemshock.zip
    name: Shockolate
  
deploy:
  - provider: GitHub
    release: Shockolate-v$(appveyor_build_version)
    description: 'Latest and greatest Shockolate for Windows'
    artifact: systemshock.zip
    auth_token:
      secure: 4oa2yc5W2R7oqYQfqkQnqi2yl0v5tSeh58GS+su7tsAXMaM77BeWhSDs+p7T4cWy

    
